version: '3.8'

services:
  backend:
    build: .
    container_name: workit
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    command: gunicorn core.wsgi --bind 0.0.0.0:8000