# Generated by Django 5.0.7 on 2024-07-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workituser',
            managers=[
            ],
        ),
    ]
