# Generated by Django 5.0.7 on 2024-07-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_workituser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workituser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
