name: Deploy

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy
        uses: actions/checkout@v4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          SCRIPT_AFTER: |
            cd /home/ubuntu/workit
            git checkout main
            git fetch --all
            git reset --hard origin/main
            git pull origin main
