name: Deploy

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_HOST }}
          ssh-user: ${{ secrets.USER_NAME }}
      - run: |
            cd /home/ubuntu/workit
            git checkout main
            git fetch --all
            git reset --hard origin/main
            git pull origin main
