name: Deploy

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy
        uses: actions/checkout@v4
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
      - run: |
          echo "$PRIVATE_KEY" > private_key && sudo chmod 400 private_key
          cat private_key
